### ISSUE TITLE
Arguments beginning with capital letters

### ISSUE THREAD

**Issue by benranderson** [rodolphebarbanneau/python-docstring-highlighter#2]
Love the extension. However, finding it doesn't seem to recognise function arguments beginning with a capital letter.

Same issue with both Google and NumPy formats:

![image](https://github.com/rodolphebarbanneau/python-docstring-highlighter/assets/8963848/be5bac7d-1d28-4432-8057-4330639a8ee5)

**Comment by rodolphebarbanneau** [comment]
Hello, thanks for your feedback!
I've updated the extension to accept parameters starting with an uppercase character.
