### ISSUE TITLE
Not Recognizing 'Dash' Argument Names

### ISSUE THREAD

**Issue by mctinker** [rodolphebarbanneau/python-docstring-highlighter#3]
The extension does not pick up names that begin with a dash.  Example:

    Parameters:
        - frame (ctk.CTkFrame): The frame to add the option menu to.
        - command (object): The function to be called when an option is selected.
       
These parameters are automatically generated for me by an AI assistant.  Is there any way you can recognize the dashes?

**Comment by rodolphebarbanneau** [comment]
Hello, thanks for your feedback!
I've updated the extension to accepts a leading hyphen before parameters.
